# fly.toml app configuration file generated for api-pets on 2023-06-08T00:31:36-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "api-pets"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
